In [82]:
from __future__ import print_function
import os
import pickle
import random
import numpy as np
import logging
from sklearn import svm, ensemble, neighbors
import math

In [2]:
data_file = 'data.csv'
data_prefix = data_file.split('.')[0]
data_pickle = data_prefix + '.pkl'

In [3]:
data = np.genfromtxt(data_file, delimiter=',')

In [4]:
data.shape

(3476, 1248)

In [14]:
X = data[:, :-6]

In [27]:
yy = data[:, -6:]

In [29]:
y = yy[:, 0]

In [25]:
clf = svm.LinearSVC()

In [30]:
clf.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [31]:
clf.predict(X[0])

array([ 34.])

In [32]:
y[0]

34.0

In [33]:
clf.predict(X[1])

array([ 34.])

In [36]:
pred_y = clf.predict(X)

In [37]:
print(np.all(pred_y==y))

False


In [38]:
pred_y

array([ 34.,  34.,  20., ...,  55.,  37.,  55.])

In [39]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [42]:
svm.LinearSVC?

In [44]:
svm.SVC?

In [45]:
from sklearn.cross_validation import train_test_split

In [46]:
train_test_split?

In [47]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [48]:
yy

array([[  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       ..., 
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ]])

In [50]:
svm.SVC?

In [51]:
yy[:, 3]

array([ 23.03 ,  23.03 ,  23.03 , ...,  21.514,  21.514,  21.514])

In [54]:
weights = yy[:, 2]

In [55]:
np.all(weights!=np.nan)

True

In [58]:
np.isnan?

In [57]:
%psource np.isnan

No source found for np.isnan


In [59]:
a = np.array([[1,2,3], [4,5,np.nan], [7,8,9]])

In [60]:
a

array([[  1.,   2.,   3.],
       [  4.,   5.,  nan],
       [  7.,   8.,   9.]])

In [61]:
a[~np.isnan(a).any(axis=1)]

array([[ 1.,  2.,  3.],
       [ 7.,  8.,  9.]])

In [62]:
a = np.array([[0,1, 2], [3, 4, 5]])

In [63]:
b = np.array([-1, -2])

In [70]:
np.vstack((a.T, b.T))

array([[ 0,  3],
       [ 1,  4],
       [ 2,  5],
       [-1, -2]])

In [71]:
np.column_stack((a,b))

array([[ 0,  1,  2, -1],
       [ 3,  4,  5, -2]])

In [83]:
ensemble.GradientBoostingClassifier?