In [67]:
from __future__ import print_function
import os
import pickle
import random
import numpy as np
import logging
from sklearn import svm, ensemble, neighbors
import math
import matplotlib.pyplot as plt

In [2]:
data_file = 'data.csv'
data_prefix = data_file.split('.')[0]
data_pickle = data_prefix + '.pkl'

In [3]:
data = np.genfromtxt(data_file, delimiter=',')

In [4]:
data.shape

(3476, 1248)

In [5]:
X = data[:, :-6]

In [6]:
yy = data[:, -6:]

In [7]:
y = yy[:, 0]

In [8]:
clf = svm.LinearSVC()

In [9]:
clf.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='l2', multi_class='ovr', penalty='l2',
     random_state=None, tol=0.0001, verbose=0)

In [10]:
clf.predict(X[0])

array([ 34.])

In [11]:
y[0]

34.0

In [12]:
clf.predict(X[1])

array([ 34.])

In [13]:
pred_y = clf.predict(X)

In [14]:
print(np.all(pred_y==y))

False


In [15]:
pred_y

array([ 34.,  34.,  20., ...,  55.,  37.,  55.])

In [16]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [17]:
svm.LinearSVC?

In [18]:
svm.SVC?

In [19]:
from sklearn.cross_validation import train_test_split

In [20]:
train_test_split?

In [21]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [22]:
yy

array([[  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       ..., 
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ]])

In [23]:
yy[:, 3]

array([ 23.03 ,  23.03 ,  23.03 , ...,  21.514,  21.514,  21.514])

In [24]:
weights = yy[:, 2]

In [25]:
np.all(weights!=np.nan)

True

In [26]:
a = np.array([[1,2,3], [4,5,np.nan], [7,8,9]])

In [27]:
a

array([[  1.,   2.,   3.],
       [  4.,   5.,  nan],
       [  7.,   8.,   9.]])

In [28]:
a[~np.isnan(a).any(axis=1)]

array([[ 1.,  2.,  3.],
       [ 7.,  8.,  9.]])

In [29]:
a = np.array([[0,1, 2], [3, 4, 5]])

In [30]:
b = np.array([-1, -2])

In [31]:
np.vstack((a.T, b.T))

array([[ 0,  3],
       [ 1,  4],
       [ 2,  5],
       [-1, -2]])

In [32]:
np.column_stack((a,b))

array([[ 0,  1,  2, -1],
       [ 3,  4,  5, -2]])

In [33]:
yy[0]

array([  34.  ,  168.  ,   65.  ,   23.03,   -1.  ,  -10.  ])

In [34]:
y0 = yy[:,0].astype(np.int32)
y0

array([34, 34, 34, ..., 55, 55, 55], dtype=int32)

In [35]:
x = np.array([1,0,2,0,3,0,4,5,6,7,8])

In [36]:
np.where(x==0)

(array([1, 3, 5]),)

In [37]:
t = np.array([ 147, 5729, 5794, 5806, 6798, 8756, 8772, 8776, 9976])
dt  = np.diff(t)
pos = np.where(dt > 100)[0] + 1
print(np.split(t, pos))

[array([147]), array([5729, 5794, 5806]), array([6798]), array([8756, 8772, 8776]), array([9976])]


In [38]:
np.bincount(y0)[34]

112

In [52]:
y0 = yy[:, 5].astype(np.int32)
uniques = np.unique(y0)

In [53]:
y0

array([-10, -10, -10, ..., -10, -10, -10], dtype=int32)

In [55]:
plt.savefig?

In [58]:
ia =np.array([[1,2,3], [4,5,6]])

In [63]:
fa = np.array([-1.0, -2.1])

In [64]:
np.column_stack((ia, fa))

array([[ 1. ,  2. ,  3. , -1. ],
       [ 4. ,  5. ,  6. , -2.1]])

In [95]:
aa = np.arange(1, 30, 4).astype(np.float64)

In [96]:
aa

array([  1.,   5.,   9.,  13.,  17.,  21.,  25.,  29.])

In [97]:
mm = np.min(aa), np.max(aa)
NUM = 5

In [101]:
division = float(mm[1]-mm[0]) / NUM
division

5.6

In [100]:
aaa = (aa - mm[0]) / division
aaa

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ])

In [88]:
np.floor()

array([ 0.,  0.,  1.,  2.,  2.,  3.,  4.,  5.])