In [9]:
from __future__ import print_function
import os
import pickle
import random
import numpy as np
import logging
from sklearn import svm

In [2]:
data_file = 'data.csv'
data_prefix = data_file.split('.')[0]
data_pickle = data_prefix + '.pkl'

In [3]:
data = np.genfromtxt(data_file, delimiter=',')

In [4]:
data.shape

(3476, 1248)

In [14]:
X = data[:, :-6]

In [27]:
yy = data[:, -6:]

In [29]:
y = yy[:, 0]

In [25]:
clf = svm.LinearSVC()

In [30]:
clf.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [31]:
clf.predict(X[0])

array([ 34.])

In [32]:
y[0]

34.0

In [33]:
clf.predict(X[1])

array([ 34.])

In [36]:
pred_y = clf.predict(X)

In [37]:
print(np.all(pred_y==y))

False


In [38]:
pred_y

array([ 34.,  34.,  20., ...,  55.,  37.,  55.])

In [39]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [41]:
counter
for i, (orig, pred) in enumerate(zip(y, pred_y)):
    if orig != pred:
        print('i={:3d}, {}'.format(i, (orig, pred)))

i=  2, (34.0, 20.0)
i=  7, (34.0, 20.0)
i= 10, (29.0, 20.0)
i= 12, (29.0, 20.0)
i= 14, (29.0, 20.0)
i= 16, (33.0, 20.0)
i= 17, (33.0, 20.0)
i= 18, (33.0, 20.0)
i= 19, (33.0, 20.0)
i= 20, (33.0, 20.0)
i= 25, (33.0, 20.0)
i= 64, (20.0, 50.0)
i= 65, (20.0, 50.0)
i= 82, (47.0, 34.0)
i= 83, (47.0, 43.0)
i= 92, (37.0, 54.0)
i= 93, (37.0, 44.0)
i= 96, (37.0, 54.0)
i=101, (46.0, 34.0)
i=115, (54.0, 52.0)
i=122, (26.0, 28.0)
i=124, (26.0, 30.0)
i=126, (26.0, 34.0)
i=134, (30.0, 39.0)
i=139, (28.0, 25.0)
i=157, (23.0, 30.0)
i=159, (23.0, 47.0)
i=160, (23.0, 34.0)
i=161, (23.0, 34.0)
i=163, (34.0, 47.0)
i=164, (34.0, 54.0)
i=166, (34.0, 33.0)
i=167, (34.0, 45.0)
i=175, (33.0, 51.0)
i=176, (33.0, 52.0)
i=177, (44.0, 32.0)
i=181, (44.0, 30.0)
i=187, (33.0, 35.0)
i=198, (47.0, 35.0)
i=200, (48.0, 30.0)
i=207, (35.0, 28.0)
i=211, (35.0, 34.0)
i=213, (35.0, 30.0)
i=218, (51.0, 25.0)
i=219, (51.0, 54.0)
i=220, (51.0, 23.0)
i=223, (45.0, 48.0)
i=224, (45.0, 33.0)
i=225, (45.0, 37.0)
i=226, (45.0, 37.0)


In [42]:
svm.LinearSVC?