In [113]:
from __future__ import print_function
import os
import pickle
import random
import numpy as np
import logging
from sklearn import svm, ensemble, neighbors
import math
import matplotlib.pyplot as plt

In [114]:
data_file = 'data.csv'
data_prefix = data_file.split('.')[0]
data_pickle = data_prefix + '.pkl'

In [115]:
data = np.genfromtxt(data_file, delimiter=',')

In [116]:
data.shape

(3476, 1248)

In [117]:
X = data[:, :-6]

In [118]:
yy = data[:, -6:]

In [119]:
y = yy[:, 0]

In [120]:
clf = svm.LinearSVC()

In [121]:
clf.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [122]:
clf.predict(X[0])

array([ 34.])

In [175]:
y[0]

34.0

In [176]:
clf.predict(X[1])

array([ 34.])

In [177]:
pred_y = clf.predict(X)

In [178]:
print(np.all(pred_y==y))

False


In [179]:
pred_y

array([ 34.,  34.,  20., ...,  55.,  37.,  55.])

In [180]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [181]:
from sklearn.cross_validation import train_test_split

In [182]:
train_test_split?

In [183]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [184]:
yy

array([[  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       ..., 
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ]])

In [185]:
yy[:, 3]

array([ 23.03 ,  23.03 ,  23.03 , ...,  21.514,  21.514,  21.514])

In [186]:
weights = yy[:, 2]

In [187]:
np.all(weights!=np.nan)

True

In [188]:
a = np.array([[1,2,3], [4,5,np.nan], [7,8,9]])

In [189]:
a

array([[  1.,   2.,   3.],
       [  4.,   5.,  nan],
       [  7.,   8.,   9.]])

In [190]:
a[~np.isnan(a).any(axis=1)]

array([[ 1.,  2.,  3.],
       [ 7.,  8.,  9.]])

In [191]:
a = np.array([[0,1, 2], [3, 4, 5]])

In [192]:
b = np.array([-1, -2])

In [193]:
np.vstack((a.T, b.T))

array([[ 0,  3],
       [ 1,  4],
       [ 2,  5],
       [-1, -2]])

In [194]:
np.column_stack((a,b))

array([[ 0,  1,  2, -1],
       [ 3,  4,  5, -2]])

In [195]:
yy[0]

array([  34.  ,  168.  ,   65.  ,   23.03,   -1.  ,  -10.  ])

In [196]:
y0 = yy[:,0].astype(np.int32)
y0

array([34, 34, 34, ..., 55, 55, 55], dtype=int32)

In [197]:
x = np.array([1,0,2,0,3,0,4,5,6,7,8])

In [198]:
np.where(x==0)

(array([1, 3, 5]),)

In [199]:
t = np.array([ 147, 5729, 5794, 5806, 6798, 8756, 8772, 8776, 9976])
dt  = np.diff(t)
pos = np.where(dt > 100)[0] + 1
print(np.split(t, pos))

[array([147]), array([5729, 5794, 5806]), array([6798]), array([8756, 8772, 8776]), array([9976])]


In [200]:
np.bincount(y0)[34]

112

In [201]:
y0 = yy[:, 5].astype(np.int32)
uniques = np.unique(y0)

In [202]:
y0

array([-10, -10, -10, ..., -10, -10, -10], dtype=int32)

In [203]:
plt.savefig?

In [204]:
ia =np.array([[1,2,3], [4,5,6]])

In [205]:
fa = np.array([-1.0, -2.1])

In [206]:
np.column_stack((ia, fa))

array([[ 1. ,  2. ,  3. , -1. ],
       [ 4. ,  5. ,  6. , -2.1]])

In [207]:
aa = np.arange(1, 30, 4).astype(np.float64)

In [208]:
aa

array([  1.,   5.,   9.,  13.,  17.,  21.,  25.,  29.])

In [209]:
mm = np.min(aa), np.max(aa)
NUM = 5

In [210]:
division = float(mm[1]-mm[0]) / NUM
division

5.6

In [211]:
aaa = (aa - mm[0]) / division
aaa

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ])

In [212]:
new_array = np.linspace(mm[0],mm[1], NUM)

In [213]:
new_array

array([  1.,   8.,  15.,  22.,  29.])

In [214]:
aa

array([  1.,   5.,   9.,  13.,  17.,  21.,  25.,  29.])

In [251]:
GROUP_NUM = 5
def try_group(label_feat):
    label_feat = label_feat[~np.isnan(label_feat)]
    # label_feat = label_feat.astype(np.int32)
    uniques = np.unique(label_feat)
    if uniques.shape[0] < GROUP_NUM:
        # print("shape={}".format(uniques.shape))
        return label_feat
    fittted_feat = np.zeros(label_feat.shape, dtype=int)
    print(np.max(label_feat), np.min(label_feat), GROUP_NUM)
    separators = np.linspace(np.min(label_feat), np.max(label_feat), GROUP_NUM)
    print(separators)
    for i in xrange(label_feat.shape[0]):
        for j in xrange(GROUP_NUM - 1):
            # print(separators[j], label_feat[i], separators[j+1])
            if separators[j] <= label_feat[i] < separators[j+1]:
                fittted_feat[i] = j
                break
        else:
            fittted_feat[i] = GROUP_NUM - 1
    return fittted_feat

In [255]:
res = yy[:, 1]
r = res[~np.isnan(res)]
r.shape

(3360,)

In [253]:
race = try_group(yy[:,1])

193.0 148.0 5
[ 148.    159.25  170.5   181.75  193.  ]


In [229]:
import collections

In [258]:
c = collections.Counter(race)
for cc in c.items():
    print('{:4d} {}'.format(cc[1], cc[1]/float(r.shape[0])))

 355 0.105654761905
1744 0.519047619048
1161 0.345535714286
  94 0.0279761904762
   6 0.00178571428571


In [280]:
w = yy[:,0]
weight = w[~np.isnan(w)]

In [281]:
np.max(weight), np.min(weight)

(69.0, 13.0)

In [275]:
aaa = np.linspace(40.0, 100.0, 5)

In [279]:
for i in range(aaa.shape[0]-1):
    print('[{}, {})'.format(aaa[i], aaa[i+1]), end=', ')

[40.0, 55.0), [55.0, 70.0), [70.0, 85.0), [85.0, 100.0), 

In [282]:
yy.shape

(3476, 6)

In [284]:
X.shape

(3476, 1242)