In [82]:
from __future__ import print_function
import os
import pickle
import random
import numpy as np
import logging
from sklearn import svm, ensemble, neighbors
import math

In [2]:
data_file = 'data.csv'
data_prefix = data_file.split('.')[0]
data_pickle = data_prefix + '.pkl'

In [3]:
data = np.genfromtxt(data_file, delimiter=',')

In [4]:
data.shape

(3476, 1248)

In [14]:
X = data[:, :-6]

In [27]:
yy = data[:, -6:]

In [29]:
y = yy[:, 0]

In [25]:
clf = svm.LinearSVC()

In [30]:
clf.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [31]:
clf.predict(X[0])

array([ 34.])

In [32]:
y[0]

34.0

In [33]:
clf.predict(X[1])

array([ 34.])

In [36]:
pred_y = clf.predict(X)

In [37]:
print(np.all(pred_y==y))

False


In [38]:
pred_y

array([ 34.,  34.,  20., ...,  55.,  37.,  55.])

In [39]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [42]:
svm.LinearSVC?

In [44]:
svm.SVC?

In [45]:
from sklearn.cross_validation import train_test_split

In [46]:
train_test_split?

In [47]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [48]:
yy

array([[  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       ..., 
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ]])

In [51]:
yy[:, 3]

array([ 23.03 ,  23.03 ,  23.03 , ...,  21.514,  21.514,  21.514])

In [54]:
weights = yy[:, 2]

In [55]:
np.all(weights!=np.nan)

True

In [59]:
a = np.array([[1,2,3], [4,5,np.nan], [7,8,9]])

In [60]:
a

array([[  1.,   2.,   3.],
       [  4.,   5.,  nan],
       [  7.,   8.,   9.]])

In [61]:
a[~np.isnan(a).any(axis=1)]

array([[ 1.,  2.,  3.],
       [ 7.,  8.,  9.]])

In [62]:
a = np.array([[0,1, 2], [3, 4, 5]])

In [63]:
b = np.array([-1, -2])

In [70]:
np.vstack((a.T, b.T))

array([[ 0,  3],
       [ 1,  4],
       [ 2,  5],
       [-1, -2]])

In [86]:
np.column_stack((a,b))

array([[ 0,  1,  2, -1],
       [ 3,  4,  5, -2]])

In [87]:
yy[0]

array([  34.  ,  168.  ,   65.  ,   23.03,   -1.  ,  -10.  ])

In [101]:
y0 = yy[:,0].astype(np.int32)
y0

array([34, 34, 34, ..., 55, 55, 55], dtype=int32)

In [93]:
x = np.array([1,0,2,0,3,0,4,5,6,7,8])

In [94]:
np.where(x==0)

(array([1, 3, 5]),)

In [96]:
t = np.array([ 147, 5729, 5794, 5806, 6798, 8756, 8772, 8776, 9976])
dt  = np.diff(t)
pos = np.where(dt > 100)[0] + 1
print(np.split(t, pos))

[array([147]), array([5729, 5794, 5806]), array([6798]), array([8756, 8772, 8776]), array([9976])]


In [102]:
np.bincount(y0)[34]

112

In [109]:
y0 = yy[:, 4].astype(np.int32)
uniques = np.unique(y0)

In [110]:
v_c_dict = {}
for u in uniques:
    v_c_dict[u] = np.bincount(y0)[u]
v_c_dict

ValueError: The first argument of bincount must be non-negative

In [107]:
yy[:,2]

array([ 65.,  65.,  65., ...,  60.,  60.,  60.])

In [111]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [112]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1])