In [74]:
from __future__ import print_function
import os
import pickle
import random
import numpy as np
import logging
from sklearn import svm
import math

In [2]:
data_file = 'data.csv'
data_prefix = data_file.split('.')[0]
data_pickle = data_prefix + '.pkl'

In [3]:
data = np.genfromtxt(data_file, delimiter=',')

In [4]:
data.shape

(3476, 1248)

In [14]:
X = data[:, :-6]

In [27]:
yy = data[:, -6:]

In [29]:
y = yy[:, 0]

In [25]:
clf = svm.LinearSVC()

In [30]:
clf.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [31]:
clf.predict(X[0])

array([ 34.])

In [32]:
y[0]

34.0

In [33]:
clf.predict(X[1])

array([ 34.])

In [36]:
pred_y = clf.predict(X)

In [37]:
print(np.all(pred_y==y))

False


In [38]:
pred_y

array([ 34.,  34.,  20., ...,  55.,  37.,  55.])

In [39]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [42]:
svm.LinearSVC?

In [44]:
svm.SVC?

In [45]:
from sklearn.cross_validation import train_test_split

In [46]:
train_test_split?

In [47]:
y

array([ 34.,  34.,  34., ...,  55.,  55.,  55.])

In [48]:
yy

array([[  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       [  34.   ,  168.   ,   65.   ,   23.03 ,   -1.   ,  -10.   ],
       ..., 
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ],
       [  55.   ,  167.   ,   60.   ,   21.514,   -1.   ,  -10.   ]])

In [50]:
svm.SVC?

In [51]:
yy[:, 3]

array([ 23.03 ,  23.03 ,  23.03 , ...,  21.514,  21.514,  21.514])

In [54]:
weights = yy[:, 2]

In [55]:
np.all(weights!=np.nan)

True

In [58]:
np.isnan?

In [57]:
%psource np.isnan

No source found for np.isnan


In [59]:
a = np.array([[1,2,3], [4,5,np.nan], [7,8,9]])

In [60]:
a

array([[  1.,   2.,   3.],
       [  4.,   5.,  nan],
       [  7.,   8.,   9.]])

In [61]:
a[~np.isnan(a).any(axis=1)]

array([[ 1.,  2.,  3.],
       [ 7.,  8.,  9.]])

In [62]:
a = np.array([[0,1, 2], [3, 4, 5]])

In [63]:
b = np.array([-1, -2])

In [65]:
np.concatenate((a, b), axis=1)

ValueError: all the input arrays must have same number of dimensions

In [66]:
len(a)

2

In [67]:
len(b)

2

In [70]:
np.vstack((a.T, b.T))

array([[ 0,  3],
       [ 1,  4],
       [ 2,  5],
       [-1, -2]])

In [71]:
np.column_stack((a,b))

array([[ 0,  1,  2, -1],
       [ 3,  4,  5, -2]])

In [81]:
counter = 0
for i,e in enumerate(yy[:,2]):
    if math.isnan(e) or math.isinf(e):
        counter += 1
        print(i,e)
print(counter)

16 nan
17 nan
18 nan
19 nan
20 nan
21 nan
22 nan
23 nan
24 nan
25 nan
26 nan
27 nan
28 nan
29 nan
30 nan
31 nan
32 nan
33 nan
34 nan
35 nan
36 nan
37 nan
38 nan
39 nan
40 nan
41 nan
42 nan
43 nan
44 nan
45 nan
46 nan
47 nan
48 nan
49 nan
50 nan
51 nan
52 nan
53 nan
54 nan
55 nan
56 nan
57 nan
58 nan
59 nan
60 nan
61 nan
62 nan
63 nan
64 nan
65 nan
66 nan
67 nan
68 nan
69 nan
70 nan
71 nan
72 nan
73 nan
74 nan
75 nan
76 nan
77 nan
78 nan
79 nan
80 nan
81 nan
1754 nan
1755 nan
1756 nan
1757 nan
1758 nan
1759 nan
1760 nan
1761 nan
1762 nan
1763 nan
1764 nan
1765 nan
1766 nan
1767 nan
1768 nan
1769 nan
1770 nan
1771 nan
1772 nan
1773 nan
1774 nan
1775 nan
1776 nan
1777 nan
1778 nan
1779 nan
1780 nan
1781 nan
1782 nan
1783 nan
1784 nan
1785 nan
1786 nan
1787 nan
1788 nan
1789 nan
1790 nan
1791 nan
1792 nan
1793 nan
1794 nan
1795 nan
1796 nan
1797 nan
1798 nan
1799 nan
1800 nan
1801 nan
1802 nan
1803 nan
1804 nan
1805 nan
1806 nan
1807 nan
1808 nan
1809 nan
1810 nan
1811 nan
1812 nan
1813 na